---
# Playbook to install one HTTPD and multiple TOMCAT servers
- hosts: localhost
  connection: local
  become_method: sudo
  become: yes
  gather_facts: no
    
  roles:
    - role: httpd
      tags: apache
    - role: tomcat
      tags: tomcat
  