---

- name: Download OpenJDK8
  get_url: url=https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm dest=/opt/jdk-8
  tag: tomcat
    
- name: Install OpenJDK8
  command: rpm -ivh /opt/jdk-8/jdk-8u201-linux-x64.rpm
  tag: tomcat
    
- name: add "tomcat" as user and group
  group: name=tomcat1
  user: name=tomcat1 group=tomcat1 createhome=no
  tag: tomcat
    
- name: "Download Tomcat 8"
  get_url: url=https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.35/bin/apache-tomcat-8.5.35.tar.gz dest=/opt
  tag: tomcat
    
- name: "Extract the Tomcat zip into 1st Tomcat instance"
  command: tar -xvf /opt/apache-tomcat-8.5.35.tar.gz -C /opt/tomcat-8-one
  tag: tomcat
   
- name: Changing the ownership of tomcat installation
  file: path=/opt/tomcat-8-one/ owner=tomcat1 group=tomcat1 state=directory recurse=yes
  tag: tomcat
    
- name: Configure Tomcat for Server 1
  tag: tomcat
  template: src=server.xml dest=/opt/tomcat-8-one/conf/
  notify: restart_tomcat
 
- name: Configure Tomcat users for server 1
  tag: tomcat
  template: src=tomcat-users.xml dest=/opt/tomcat-8-one/conf/
  notify: restart_tomcat
  
- name: Install the Tomcat service script
  copy: src=tomcat-service.sh dest=/etc/init.d/tomcat1 mode=0755
  tag: tomcat

- name: Running Tomcat 8 as service
  service: name=tomcat1 state=started enabled=yes
  tag: tomcat